package theilluminatigame;

import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;

/**
 *
 * @author zhongyuwang
 */
public class gameUI extends javax.swing.JFrame {
    
    private int xMouse;
    private int yMouse;
    private boolean maximized = true;
    
    /**
     * Creates new form gameUI
     */
    public gameUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        leftSideBar = new javax.swing.JPanel();
        Close_BTN = new javax.swing.JLabel();
        Minimum_BTN = new javax.swing.JLabel();
        Maximum_BTN = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        RightContainer = new javax.swing.JPanel();
        DisplayArea = new javax.swing.JPanel();
        Player_1 = new javax.swing.JPanel();
        Player_2 = new javax.swing.JPanel();
        Player_3 = new javax.swing.JPanel();
        Player_4 = new javax.swing.JPanel();
        Dead_Pile = new javax.swing.JPanel();
        Uncontrolled_Groups = new javax.swing.JPanel();
        Bank = new javax.swing.JPanel();
        Face_Down_Pile = new javax.swing.JPanel();
        Player_5 = new javax.swing.JPanel();
        Player_6 = new javax.swing.JPanel();
        Player_7 = new javax.swing.JPanel();
        Player_8 = new javax.swing.JPanel();
        UerActionArea = new javax.swing.JPanel();
        Action_1 = new javax.swing.JLabel();
        Action_2 = new javax.swing.JLabel();
        Action_3 = new javax.swing.JLabel();
        Action_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        leftSideBar.setBackground(new java.awt.Color(0, 0, 51));
        leftSideBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                leftSideBarMouseDragged(evt);
            }
        });
        leftSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leftSideBarMousePressed(evt);
            }
        });

        Close_BTN.setBackground(new java.awt.Color(255, 255, 255));
        Close_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Close_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IlluminatiCards/Delete_ffffff_25.png"))); // NOI18N
        Close_BTN.setToolTipText("Exit");
        Close_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Close_BTNMouseReleased(evt);
            }
        });

        Minimum_BTN.setBackground(new java.awt.Color(255, 255, 255));
        Minimum_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Minimum_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IlluminatiCards/Minimize Window_ffffff_25.png"))); // NOI18N
        Minimum_BTN.setToolTipText("Minimize");
        Minimum_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Minimum_BTNMouseReleased(evt);
            }
        });

        Maximum_BTN.setBackground(new java.awt.Color(255, 255, 255));
        Maximum_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Maximum_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IlluminatiCards/Maximize Window_ffffff_25.png"))); // NOI18N
        Maximum_BTN.setToolTipText("Maximize");
        Maximum_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Maximum_BTNMouseReleased(evt);
            }
        });

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IlluminatiCards/Gallery_100.png"))); // NOI18N
        logo.setToolTipText("Illuminati Card Game");

        javax.swing.GroupLayout leftSideBarLayout = new javax.swing.GroupLayout(leftSideBar);
        leftSideBar.setLayout(leftSideBarLayout);
        leftSideBarLayout.setHorizontalGroup(
            leftSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Maximum_BTN)
                    .addComponent(Close_BTN)
                    .addComponent(Minimum_BTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftSideBarLayout.setVerticalGroup(
            leftSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftSideBarLayout.createSequentialGroup()
                        .addComponent(Close_BTN)
                        .addGap(18, 18, 18)
                        .addComponent(Minimum_BTN)
                        .addGap(18, 18, 18)
                        .addComponent(Maximum_BTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RightContainer.setBackground(new java.awt.Color(217, 219, 214));

        DisplayArea.setBackground(new java.awt.Color(237, 229, 204));
        DisplayArea.setLayout(new java.awt.GridLayout(3, 4));

        Player_1.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_1Layout = new javax.swing.GroupLayout(Player_1);
        Player_1.setLayout(Player_1Layout);
        Player_1Layout.setHorizontalGroup(
            Player_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_1Layout.setVerticalGroup(
            Player_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_1);

        Player_2.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_2Layout = new javax.swing.GroupLayout(Player_2);
        Player_2.setLayout(Player_2Layout);
        Player_2Layout.setHorizontalGroup(
            Player_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_2Layout.setVerticalGroup(
            Player_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_2);

        Player_3.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_3Layout = new javax.swing.GroupLayout(Player_3);
        Player_3.setLayout(Player_3Layout);
        Player_3Layout.setHorizontalGroup(
            Player_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_3Layout.setVerticalGroup(
            Player_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_3);

        Player_4.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_4Layout = new javax.swing.GroupLayout(Player_4);
        Player_4.setLayout(Player_4Layout);
        Player_4Layout.setHorizontalGroup(
            Player_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_4Layout.setVerticalGroup(
            Player_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_4);

        Dead_Pile.setBackground(new java.awt.Color(237, 229, 204));
        Dead_Pile.setLayout(new java.awt.CardLayout());
        DisplayArea.add(Dead_Pile);

        Uncontrolled_Groups.setBackground(new java.awt.Color(237, 229, 204));
        Uncontrolled_Groups.setLayout(new java.awt.GridLayout());
        DisplayArea.add(Uncontrolled_Groups);

        Bank.setBackground(new java.awt.Color(237, 229, 204));
        Bank.setLayout(new java.awt.CardLayout());
        DisplayArea.add(Bank);

        Face_Down_Pile.setBackground(new java.awt.Color(237, 229, 204));
        Face_Down_Pile.setLayout(new java.awt.CardLayout());
        DisplayArea.add(Face_Down_Pile);

        Player_5.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_5Layout = new javax.swing.GroupLayout(Player_5);
        Player_5.setLayout(Player_5Layout);
        Player_5Layout.setHorizontalGroup(
            Player_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_5Layout.setVerticalGroup(
            Player_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_5);

        Player_6.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_6Layout = new javax.swing.GroupLayout(Player_6);
        Player_6.setLayout(Player_6Layout);
        Player_6Layout.setHorizontalGroup(
            Player_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_6Layout.setVerticalGroup(
            Player_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_6);

        Player_7.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_7Layout = new javax.swing.GroupLayout(Player_7);
        Player_7.setLayout(Player_7Layout);
        Player_7Layout.setHorizontalGroup(
            Player_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_7Layout.setVerticalGroup(
            Player_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_7);

        Player_8.setBackground(new java.awt.Color(237, 229, 204));

        javax.swing.GroupLayout Player_8Layout = new javax.swing.GroupLayout(Player_8);
        Player_8.setLayout(Player_8Layout);
        Player_8Layout.setHorizontalGroup(
            Player_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        Player_8Layout.setVerticalGroup(
            Player_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        DisplayArea.add(Player_8);

        UerActionArea.setBackground(new java.awt.Color(237, 229, 214));

        Action_1.setText("Action_1");

        Action_2.setText("Action_2");

        Action_3.setText("Action_1");

        Action_4.setText("Action_4");

        javax.swing.GroupLayout UerActionAreaLayout = new javax.swing.GroupLayout(UerActionArea);
        UerActionArea.setLayout(UerActionAreaLayout);
        UerActionAreaLayout.setHorizontalGroup(
            UerActionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UerActionAreaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Action_1)
                .addGap(18, 18, 18)
                .addComponent(Action_2)
                .addGap(18, 18, 18)
                .addComponent(Action_3)
                .addGap(18, 18, 18)
                .addComponent(Action_4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UerActionAreaLayout.setVerticalGroup(
            UerActionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UerActionAreaLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(UerActionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Action_1)
                    .addComponent(Action_2)
                    .addComponent(Action_3)
                    .addComponent(Action_4))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout RightContainerLayout = new javax.swing.GroupLayout(RightContainer);
        RightContainer.setLayout(RightContainerLayout);
        RightContainerLayout.setHorizontalGroup(
            RightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
                    .addComponent(UerActionArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RightContainerLayout.setVerticalGroup(
            RightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UerActionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void Close_BTNMouseReleased(java.awt.event.MouseEvent evt) {                                        
        System.exit(0);
    }                                       

    private void Minimum_BTNMouseReleased(java.awt.event.MouseEvent evt) {                                          
        this.setState(gameUI.ICONIFIED);
    }                                         

    private void leftSideBarMouseDragged(java.awt.event.MouseEvent evt) {                                         
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }                                        

    private void leftSideBarMousePressed(java.awt.event.MouseEvent evt) {                                         
        xMouse = evt.getX();
        yMouse = evt.getY();
    }                                        

    private void Maximum_BTNMouseReleased(java.awt.event.MouseEvent evt) {                                          
        if(maximized){
            gameUI.this.setExtendedState(JFrame.MAXIMIZED_BOTH);  
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();  
            gameUI.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Action_1;
    private javax.swing.JLabel Action_2;
    private javax.swing.JLabel Action_3;
    private javax.swing.JLabel Action_4;
    private javax.swing.JPanel Bank;
    private javax.swing.JLabel Close_BTN;
    private javax.swing.JPanel Dead_Pile;
    private javax.swing.JPanel DisplayArea;
    private javax.swing.JPanel Face_Down_Pile;
    private javax.swing.JLabel Maximum_BTN;
    private javax.swing.JLabel Minimum_BTN;
    private javax.swing.JPanel Player_1;
    private javax.swing.JPanel Player_2;
    private javax.swing.JPanel Player_3;
    private javax.swing.JPanel Player_4;
    private javax.swing.JPanel Player_5;
    private javax.swing.JPanel Player_6;
    private javax.swing.JPanel Player_7;
    private javax.swing.JPanel Player_8;
    private javax.swing.JPanel RightContainer;
    private javax.swing.JPanel UerActionArea;
    private javax.swing.JPanel Uncontrolled_Groups;
    private javax.swing.JPanel leftSideBar;
    private javax.swing.JLabel logo;
    // End of variables declaration                   
}
